import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RosterContext from "./contexts/RosterContext";
import PokemonRoster from "./components/PokemonRoster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RosterContext>
          <main>
            <div className="flex h-screen">
              <div className="w-1/4 max-w-48 bg-gray-200 p-4">
                <PokemonRoster></PokemonRoster>
              </div>
              <div className="flex-1 overflow-y-auto p-4">{children}</div>
            </div>
          </main>
        </RosterContext>
      </body>
    </html>
  );
}
